version: '3'
services:

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: 0verDistribution
    restart: unless-stopped
    tty: true
    volumes:
#      - /var/log/nginx:/var/log/nginx
      - ./app/dist/:/usr/share/nginx/html/school_allstudent/
