version: '3.7'

networks:
  bridge:
    external:
      name: ${NETWORKS}

services:
  distribution:
    image: nginx:alpine
    container_name: 0verDistribution
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./app/dist/:/usr/share/nginx/html/school_allstudent/
    networks:
      - bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.distribution.entrypoints=websecure"
      - "traefik.http.routers.distribution.tls.certresolver=lets-encr"
      - "traefik.http.routers.distribution.rule=Host(``) && PathPrefix(`/school_allstudent`)"
